name: Rust Format Check

on:
    pull_request:
        paths:
            - 'datagen/**'
        branches:
            - '*'
    push:
        paths:
            - 'datagen/**'
        branches:
            - main

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy

    - name: Check Formatting
      run: |
        cd datagen
        cargo test --all-features
