name: Rust Format Check

on:
    pull_request:
        branches:
            - '*'
    push:
        branches:
            - main

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    
    - name: Install cargo-fmt
      run: rustup component add rustfmt

    - name: Check Formatting
      run: |
        cd datagen
        cargo fmt -- --check
