name: Rust Run Tests

on:
    pull_request:
        paths:
            - 'datagen/**'
        branches:
            - '*'
    push:
        paths:
            - 'datagen/**'
        branches:
            - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Run tests 
      run: |
        cd datagen
        cargo test --all-features
