name: Automatic Datagen

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *'

jobs:
    test-commit-and-pr:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Rust toolchain
              uses: dtolnay/rust-toolchain@stable

            - name: Set up Git with new branch
              run: |
                git config --global user.name 'GitHub Action'
                git config --global user.email 'action@github.com'
                git fetch
                git checkout data-update
            
            - name: Edit datagen-runs.txt
              run: |
                echo "\n$(date +%Y%m%d)" >> datagen-runs.txt

            # - name: Run datagen
            #   run: |
            #     cd datagen
            #     cargo run
            #     cd ..

            - name: Commit and push to origin
              run: |
                git add --all
                git commit -m "Daily automated datagen" || exit 0
                git push origin HEAD

            - name: Open pull request
              run: |
                echo "RUNDATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
                gh pr create -B main -H data-update --title '[AUTOMATED] Automatic Datagen $RUNDATE' --body 'Run datagen; automated, created by GitHub Action.'
                gh pr edit data-update --add-label AUTOMATED
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Merge pull request
              run: gh pr merge data-update --admin --squash
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}