name: Test Cron-Triggered Action

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *'

jobs:
    test-commit-and-pr:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Rust toolchain
              uses: dtolnay/rust-toolchain@stable

            - name: Set up Git with new branch
              run: |
                git config --global user.name 'GitHub Action'
                git config --global user.email 'action@github.com'
                git fetch
                git checkout data-update
            
            - name: Edit datagen-runs.txt
              run: |
                touch $(date +%Y%m%d)
                echo "$(date +%Y%m%d)" >> datagen-runs.txt

            - name: Run datagen
              run: |
                cd datagen
                cargo run
                cd ..

            - name: Commit and push to origin
              run: |
                git add --all
                git commit -m "Test daily run with commit" || exit 0
                git push origin HEAD

            # - name: Push changes
            #   uses: ad-m/github-push-action@master
            #   with:
            #     github_token: ${{ secrets.GITHUB_TOKEN }}
            #     branch: data-update

            - name: Open pull request
              run: |
                gh pr create -B main -H data-update --title 'Test Automated Update' --body 'Test daily run with commit; Created by GitHub Action'
                gh pr edit data-update --add-label AUTOMATED
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}