name: Test Cron-Triggered Action

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *'

jobs:
    test-commit-and-pr:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Git with new branch
              run: |
                git config --global user.name 'GitHub Action'
                git config --global user.email 'action@github.com'
                git checkout data-update
            
            - name: Create new file, commit, and PR
              run: |
                touch $(date +%Y%m%d)
                git add --all
                git commit -m "Test daily run with commit" || exit 0
                git push origin HEAD

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: data-update
            
            - name: Open pull request
              uses: peter-evans/create-pull-request@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                commit_message: Test daily run with commit
                title: 'Test Automated Update $(date +$(date +%Y%m%d))'
                branch: data-update
                delete_branch_after_merge: true
                labels: |
                    AUTOMATED


            - name: Set up Rust toolchain
              uses: dtolnay/rust-toolchain@stable