name: ESLint on Site Directory

on: 
    pull_request:
        paths:
        - 'site/**'  # Trigger only when changes are made in the 'site' directory
        branches: '*'
    push:
        paths:
        - 'site/**'
        branches: main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.13'

    - name: Install Dependencies
      run: npm install
      working-directory: ./site  # Specify the working directory

    - name: Run ESLint
      run: npx eslint .  # ESLint will run in the 'site' directory
      working-directory: ./site  # Specify the working directory
