name: PR Branch Check

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  check-pr-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR branch does not start with 'dev'
        id: check_branch
        run: |
          if [[ ! "${{ github.head_ref }}" == dev* ]]; then
            echo "branch_check_failed=true" >> $GITHUB_ENV
          fi

      - name: Comment on PR
        if: env.branch_check_failed == 'true'
        run: |
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            -d '{"body":"🚨 Hi @${{ github.actor }}, are you sure you want to merge directly into the `main` branch and not a development branch? Please check the box to confirm:\n- [ ] I, @${{ github.actor }}, confirm that `main` is the intended target branch of this pull request."}'