name: Comment on PRs to `main`

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  check-pr-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR branch does not start with 'dev'
        run: |
          if [[ ! "${{ github.head_ref }}" == dev* ]]; then
            echo "branch_check_failed=true" >> $GITHUB_ENV
          fi
      
      - name: Check if PR branch does start with 'dev'
        run: |
          if [[ "${{ github.head_ref }}" == dev* ]]; then
            echo "branch_check_failed=false" >> $GITHUB_ENV
          fi

      - name: Comment on PR if branch does not start with 'dev'
        if: env.branch_check_failed == 'true'
        run: |
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            -d '{"body":"🚨 Hi @${{ github.actor }}, are you sure you want to merge directly into the `main` branch and not a development branch? Please check the box to confirm:\n- [ ] I, @${{ github.actor }}, confirm that `main` is the intended target branch of this pull request."}'

      - name: Comment on PR if branch is a 'dev' branch
        if: env.branch_check_failed == 'false'
        run: |
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            -d '{"body":"Before merging this `dev` branch to main, ensure the following items are complete:\n- [ ] Add changes to the Changelog and to #253\n- [ ] Check accessibility tooltip text for all components\n- [ ] Test usability on both Chrome and Firefox\n- [ ] Test usability on all screen sizes, including mobile\n- [ ] Stage all associated issues to be closed when this PR merges and label them with `waiting`"}'